### ISSUE TITLE
new_post - datetime issue.

### ISSUE THREAD

**Issue by thomasw** [thomasw/pyposterous#1]
When posting new articles with Pyposterous, the datetime that's specified is stored 7 hours behind GMT, with an additional -7 hour GMT offset specified.

This is a problem with the Posterous API, not Pyposterous. Curl example:
    mercury:~ twelfley$ curl -u USERNAME:PASSWORD -d date=Sat%2C+24+Apr+2010+17%3A53%3A45+%2B0000 http://posterous.com/api/newpost
    <?xml version="1.0" encoding="UTF-8"?>
    <rsp stat="ok">
      <post>
        <id>17242799</id>
        <url>http://post.ly/ctI8</url>
        <longurl>http://pyposttest.posterous.com/17242799</longurl>
        <title>Untitled</title>
        <commentsenabled>true</commentsenabled>
      </post>
    </rsp>

```
mercury:~ twelfley$ curl -u USERNAME:PASSWORD -d site_id=1267571 -d num_posts=1 http://posterous.com/api/readposts
<?xml version="1.0" encoding="UTF-8"?>
<rsp stat="ok">
<post>
  <url>http://post.ly/ctI8</url>
  <link>http://pyposttest.posterous.com/17242799</link>
  <title>Untitled</title>
  <id>17242799</id>
  <body>
    <![CDATA[]]>
  </body>
  <date>Sat, 24 Apr 2010 03:53:45 -0700</date>
  <views>0</views>
  <private>false</private>
  <author>pyposttest</author>
  <authorpic>http://posterous.com/images/profile/unknown35.gif</authorpic>
  <commentsenabled>true</commentsenabled>
  <commentsCount>0</commentsCount>
</post>
</rsp>
```

**Comment by thomasw** [comment]
I thought I could fix this by just adding 7 hours to all times sent to Posterous, but doing that causes Posterous return an error saying that dates can't be in the future.

**Comment by thinktopdown** [comment]
What timezone are you in?

**Comment by thinktopdown** [comment]
we are working properly supporting timezones soon. as you point out, they are not handled correctly. its high on our list to fix. i'll keep you posted.

**Comment by thomasw** [comment]
Thanks for the update! My timezone is currently eastern daylight time (GMT -4:00). If there's anything I can do to help, let me know.

**Comment by thinktopdown** [comment]
timezones changes should be in.

**Comment by thomasw** [comment]
Thanks so much for the update. It's entirely possible I'm just missing something here, but I'm still seeing the same behavior described above.

Submitting a post with Sun 22 Aug 2010 01:30:45 +0000 is returning Sat, 21 Aug 2010 11:30:45 -0700.

That appears to be GMT -1400, not -0700 as the returned timestamp indicates.

I'll be the first to admit that timezones aren't exactly a strength of mine. I typically store everything in UTC and just use javascript to convert the timestamp to the local timezone on client machines (http://github.com/thomasw/humane_date).

I'll play with it a bit more in a week or so and maybe I can figure this out. I'm moving out to San Francisco and I need to be focusing on getting my portfolio ready for the impending job hunt.
