### ISSUE TITLE
pyposterous on PyPI

### ISSUE THREAD

**Issue by ghost** [thomasw/pyposterous#3]
Hello,

Thanks for creating the wonderful pyposterous library. But is there any reason why it is not listed in PyPI?

**Comment by thomasw** [comment]
Hi Sramana,

Thanks for the kind words. There's actually two reasons it isn't in PyPi.
1. The last time I ran the pyposterous' tests, I noticed a few failures. I haven't had time to check them out yet.  
2. Version 2 of the Posterous API is up and this thing really needs to be updated to take advantage of the the new version. (Hurray to ripping out the XML parsing crap!)

Unfortunately, I haven't had time to do either of these things lately.

In the meantime, you can install it like so if you use pip (which I highly recommend):  

```
 pip install -e git+http://github.com/thomasw/pyposterous.git#egg=pyposterous
```

**Comment by thomasw** [comment]
It looks like I didn't get to this before Posterous ceased to exist. Sorry, @sramana :(
